"""init schema

Revision ID: 62da9e0b15c3
Revises: 
Create Date: 2026-02-28 12:48:45.785865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62da9e0b15c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('preset_name', sa.String(length=64), nullable=True),
    sa.Column('model_url', sa.String(length=512), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_models_created_at'), 'user_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_models_id'), 'user_models', ['id'], unique=False)
    op.create_index(op.f('ix_user_models_user_id'), 'user_models', ['user_id'], unique=False)
    op.create_table('interaction_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_text', sa.String(length=300), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('input_count', sa.Integer(), nullable=False),
    sa.Column('output_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['user_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_sessions_id'), 'interaction_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_interaction_sessions_model_id'), 'interaction_sessions', ['model_id'], unique=False)
    op.create_index(op.f('ix_interaction_sessions_started_at'), 'interaction_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_interaction_sessions_user_id'), 'interaction_sessions', ['user_id'], unique=False)
    op.create_table('interaction_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interaction_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_events_created_at'), 'interaction_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_interaction_events_id'), 'interaction_events', ['id'], unique=False)
    op.create_index(op.f('ix_interaction_events_role'), 'interaction_events', ['role'], unique=False)
    op.create_index(op.f('ix_interaction_events_session_id'), 'interaction_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_events_session_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_role'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_id'), table_name='interaction_events')
    op.drop_index(op.f('ix_interaction_events_created_at'), table_name='interaction_events')
    op.drop_table('interaction_events')
    op.drop_index(op.f('ix_interaction_sessions_user_id'), table_name='interaction_sessions')
    op.drop_index(op.f('ix_interaction_sessions_started_at'), table_name='interaction_sessions')
    op.drop_index(op.f('ix_interaction_sessions_model_id'), table_name='interaction_sessions')
    op.drop_index(op.f('ix_interaction_sessions_id'), table_name='interaction_sessions')
    op.drop_table('interaction_sessions')
    op.drop_index(op.f('ix_user_models_user_id'), table_name='user_models')
    op.drop_index(op.f('ix_user_models_id'), table_name='user_models')
    op.drop_index(op.f('ix_user_models_created_at'), table_name='user_models')
    op.drop_table('user_models')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
